#ifndef LIB_STATEMACHINE_STATES_H
#define LIB_STATEMACHINE_STATES_H

enum States
{
    STATE_IDLE = 0,
    STATE_ACTIVE = 1,
    STATE_DISABLED = 2,
    STATE_ERROR = -1,
};

#endif // LIB_STATEMACHINE_STATES_H