// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgsm1TaoWIXO0r_qg1AHQU-UzMD_wjkyw',
    appId: '1:790868390085:web:281ab4e9a493a7e11840ac',
    messagingSenderId: '790868390085',
    projectId: 'gate-17bf0',
    authDomain: 'gate-17bf0.firebaseapp.com',
    storageBucket: 'gate-17bf0.appspot.com',
    measurementId: 'G-DTLWSE6BLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRYuO-66ALqFyxhjBR-uYZtO84CFSIhxU',
    appId: '1:790868390085:android:a28e9ff2513b18cf1840ac',
    messagingSenderId: '790868390085',
    projectId: 'gate-17bf0',
    storageBucket: 'gate-17bf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlY6VVZ3zo-wTUmoEwqXMVhcPZqOLpNXI',
    appId: '1:790868390085:ios:05b48da778b1a4651840ac',
    messagingSenderId: '790868390085',
    projectId: 'gate-17bf0',
    storageBucket: 'gate-17bf0.appspot.com',
    iosBundleId: 'com.ndomx.gate',
  );

}