export enum ErrorCodes {
  USER_NOT_FOUND = 1,
  ACCESS_DENIED = 2,
  DEVICE_NOT_FOUND = 3,
  DATABASE_ERROR = 4,
  ROOT_NOT_FOUND = 5,
  NOT_DEVICE = 6,
  NOT_ADMIN = 7,
  PATH_ERROR = 8,
  GATE_ERROR = 9,
  NODE_NOT_FOUND = 10,
  INVALID_REQUEST = 11,
}
